language: python
script: echo notest
deploy:
  provider: pypi
  twine: 1.12.1
  user: "__token__"
  password:
    secure: AyiUATmELSzHO+8rmxitANFwDy7JB4qbeZcOcAHvv+ujuliFrVgpUbuUI0/981MriAPY/v/mc/cj01WGwPGAbG3IXIW4p2w9QuBJENqSmXCo7ScQ1/yC+CF7px/ytHsFTVToAzOPQw+V72N0pGb8p1QTHOHPwTerI1Mxj6pBjjTnRWo5hWvx07NHMOSCBckYGcN7xOcYOz+sZQcfqM6Jito6aAenw1pu9hYoifhpxhVXhdHfh+n7josQg//6uz8CdEBT4q1AbAylpFS48/dxmwVEDsFIr5Wj+GPUcqSYNAlc1DHKBukpb98+nVVtvktFXsGXvYuCWEniCOfkF3qgXKJYII5+4AK1NVTOUzipo3Oi/V3GoO0sFMtJmSUfECbEp2AIjTcuz8k1Wb14QRw9aeNpr13oaVE4hRqKl9tDOI2X2tceG7o/QPCXvT8PRtXB22NUSADse+QKheyEdyo7qCZfsYzU0DIFNbqKZ/PgCMXTo8ArATI2QnAnMv7/zA35OuI97yQDoEzIUEKrot9CJPDfB1H17HheV+2AGQYhlIFxPzEtGrSQeN8dvTR0Bo9O/1BGej6gQotLohhsmNYtV+ePcyQaR1LCey2bPGbkLG3k2ZkSdgx1Ab45NYRp2ZCH4Z3P9ew9KvaPxyqR3000O4eEwbrFXT/fpSXoODqcRj4=
  on:
    branch: visualpriors
    tags: true
install:
- pip install -q -r requirements.txt
